name: Build for Windows ARM64

on:
  push:

jobs:
  build-windows-arm64:
    name: Build
    runs-on: ubuntu-latest
    env:
      llvm_path: "${{ github.workspace }}/llvm-mingw"
      texlive_commit_id: "72e553ad9359226fae15e67b0af8632b2b0ba132"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install \
            build-essential p7zip cmake ninja-build pkg-config autoconf automake autoconf-archive make texinfo bison flex m4 libtool libx11-dev
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/20220906/llvm-mingw-20220906-ucrt-ubuntu-18.04-x86_64.tar.xz
          tar -xf llvm-mingw-*.tar.xz
          mv llvm-mingw-20220906-ucrt-ubuntu-18.04-x86_64 llvm-mingw
          
      - name: Setup a new (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11 # Always specify the specific _version_ of the
                                  # action you need, `v11` in this case to stay up
                                  # to date with fixes on the v11 branch
        with:
          vcpkgGitCommitId: 'b322364f06308bdd24823f9d8f03fe0cc86fd46f'

      - name: Cache TL host tool
        id: cache-tl-host-bin
        uses: actions/cache@v3
        with:
          path: tl-host-bin
          key: ${{ runner.os }}-tl-host-bin

      - name: Build TL host tools
        if: steps.cache-tl-host-bin.outputs.cache-hit != 'true'
        run: |
          # wget https://mirrors.ctan.org/systems/texlive/Source/texlive-20240311-source.tar.xz
          # tar xf texlive-20240311-source.tar.xz
          # cd texlive-20240311-source
          git clone https://github.com/TeX-Live/texlive-source
          cd texlive-source
          git checkout ${{ env.texlive_commit_id }}
          mkdir build-linux
          cd build-linux
          ../configure --disable-all-pkgs --enable-web2c 
          make -j $(nproc) || true
          mkdir -p ${{ github.workspace }}/tl-host-bin
          cp ./texk/web2c/tangle ${{ github.workspace }}/tl-host-bin
          cp ./texk/web2c/ctangle ${{ github.workspace }}/tl-host-bin
          cp ./texk/web2c/otangle ${{ github.workspace }}/tl-host-bin
          cp ./texk/web2c/himktables ${{ github.workspace }}/tl-host-bin
          cp ./texk/web2c/tie ${{ github.workspace }}/tl-host-bin

      - name: Install dependencies from vcpkg
        run: |
          PATH=$PATH:${{ env.llvm_path }}/bin
          # tell vcpkg to only build Release variants of the dependencies
          cd ${{ env.RUNVCPKG_VCPKG_ROOT }}
          echo "set(VCPKG_BUILD_TYPE release)" >> triplets/community/arm64-mingw-dynamic.cmake
          echo "set(VCPKG_BUILD_TYPE release)" >> triplets/community/arm64-mingw-static.cmake
          packages='zziplib icu harfbuzz[graphite2] cairo pixman libgd freetype libpng'
          ./vcpkg upgrade 
          ./vcpkg install $packages --triplet arm64-mingw-dynamic --host-triplet=x64-linux-release --clean-after-build
          cd installed/arm64-mingw-dynamic/lib/
          ln libzlib.dll.a libz.dll.a

      - name: Build
        run: |
          PATH=$PATH:${{ github.workspace }}/tl-host-bin
          vcpkg_dir=${{ env.RUNVCPKG_VCPKG_ROOT }}
          chmod 755 build-cross.sh
          ./build-cross.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: temp-upload
          path: upload

  package:
    name: Package
    needs: [build-windows-arm64] # build-linux-win,macosx-qt5 is disabled
    runs-on: windows-latest
    
    steps:
      - name: Download temp artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: temp-upload

      - uses: geekyeggo/delete-artifact@v5
        with:
          name: temp-upload

      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: p7zip mingw-w64-ucrt-x86_64-ntldd

      - name: copy dlls in MSYS2
        shell: msys2 {0}
        run: |       
          cd temp-upload
          ntldd -R --search-dir ./vcpkg-dll windows/*.exe | awk '{print $3}'| grep vcpkg  | sed 's|\\|/|g' | xargs -I{} cp -u {} windows
          7z a -mx9 texlive-mingw-arm64.7z windows
          mv texlive-mingw-arm64.7z ..

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: texlive-mingw-arm64
          path: texlive-mingw-arm64.7z
